spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practical
    username: user
    password: practical
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.sql
    enabled: true
    drop-first: false