spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

jwt:
  secret: your_jwt_secret
  expiration: 3600000